### ISSUE TITLE
Frends.SFTP.DownloadFiles: Server fingerprint is causing System.FormatException

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.SFTP#46]
When you give a value for Server Fingerprint, Frends will throw this error:
![image](https://user-images.githubusercontent.com/36008914/182620317-0f40ad3a-997c-485a-9586-8b1bae09dc5d.png)

The error is possible to reproduce by giving this value for server fingerprint: `yQ3EwlmcHWm1trhaESHH1G9xm41e7jvOrG4`
![image](https://user-images.githubusercontent.com/36008914/182620913-52f2ce93-d4c3-43ca-bf3b-655302d1227d.png)

Debugging the test shows that the error is produced here: https://github.com/FrendsPlatform/Frends.SFTP/blob/main/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Util.cs#L41

According this conversation: https://stackoverflow.com/questions/17360839/conversion-to-byte-gives-this-error-input-string-was-not-in-a-correct-format it would seem that the method only accepts strings which contains only numbers. Hence, another method for byte array calculation has to be selected.

**Comment by jefim** [comment]
The problem seems to be that the Sha256 hash that was fed into the task was not in HEX format, but was in base64 format, which the task is not handling properly. I think we can easily add functionality to recognise base64 sha256 hashes and work with them. Until then a workaround would be to use HEX format instead of base64 for sha256 hashes.

**Comment by jefim** [comment]
Also, we need to return a better error message when hash verification fails, instead of what we return now.

**Comment by RikuVirtanen** [comment]
The server fingerprint is handled the same way in every SFTP task. I can try to fix this and implement the changes to all of the tasks when finished.

**Comment by RikuVirtanen** [comment]
This has been fixed in #53. This needs to be fixed to other SFTP tasks as well.
