### ISSUE TITLE
Frends.SFTP.DownloadFiles error handler needs a fix

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.SFTP#51]
Task's error handling needs to check if connection is still alive. At this moment task doesn't do that and in case connection has been lost during transfer source file action rename and move can't be resolved back to starting point. Either every file needs it's own connection or cleanup / error handling needs it's own connection.

**Comment by Asterisk123** [comment]
Hi Riku, I upgraded the task from 1.0.4. to 2.0.2 and didn't know I should fill in Temporary Work Dir (As there is no change history in tasks.frends.com that is linked in task information). This caused in my case that task removes files from SFTP although according log it doesn't even find any files. In my case there were several files matching the file mask. 
Would it be possible to set Work Dir as mandatory parameter?

**Comment by RikuVirtanen** [comment]
Hi, the change was done so that if the Temporary Work Dir is not set the task will use local Temp directory %TEMP% as temporary work dir. These changes are located in the CHANGELOG.md file in the task's repository. Unfortunately they are not yet in the documentation page tasks.frends.com. Did you have source operation on move or rename and did you have option RenameSourceFileBeforeTransfer enabled? If so the source file could be in another name or moved to another folder. If the SourceFileBeforeTrasnfer option is enabled the source file could be named to different filename that ends with .8CO extension.

**Comment by Asterisk123** [comment]
Hi, we have been chatting about this via support ticket today. But just to confirm here that source operation I had was "Move" and both rename source and destination file were enabled. We had Cobalt doing the same before and the same settings were used for rename and move within the source SFTP server. No files with temporary name can be found from source, target or %TEMP% (but of course temp that might have been emptied before I started looking).

**Comment by RikuVirtanen** [comment]
This was fixed in PR #64
