### ISSUE TITLE
Frends.SFTP.DownloadFiles relative paths

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.SFTP#55]
The relative paths seems to not work correctly. This results to the task not able to find files in other directories other than users home directory.

**Comment by Asterisk123** [comment]
Could this cause issue also with source operation "move", when moving the file inside SFTP to a relative path?

**Comment by RikuVirtanen** [comment]
Yes. At the moment it seems that the task can't access any paths that are above the user's home directory. The task should throw exception if it can't find the directory in source operation Move. This needs to be also resolved.

**Comment by RikuVirtanen** [comment]
Also absolute paths seem to give errors when the start of the path is in upper level than the user's home directory.

**Comment by RikuVirtanen** [comment]
@AapoTammisto I tested this forgotten bug with the newest version of the task and everything seems to be working correctly in my tests. I could use relative and absolute paths when downloading the file. Also I managed to move files between different parent directories using relative and absolute paths as long as the user had permissions for the directories. Could you test if the newest version 2.5.1 has fixed this issue on your case?

**Comment by AapoTammisto** [comment]
@RikuVirtanen Perfect!
I will test this and let you know. Will take some time though.

**Comment by RikuVirtanen** [comment]
Closing this as fixed. This is possibly fixed in some PR without knowing.
