### ISSUE TITLE
Frends.SFTP.DownloadFiles

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.SFTP#9]
- Cobalt as example (https://github.com/FrendsPlatform/Frends.Cobalt/tree/master#source)
- File masks need to be supported
- All current Cobalt connection parameters need to be supported for SFTP (auth methods, server thumbprint, large buffers etc)
- No need for prcessing steps
- Options should be supported as much as possible
  - Concurrect connections
  - Renames
  - Create directory structure
  - Destination file exists action
  - No source action
  - Source operation
  - Preserve modified
  - Operation log, also this should be true by default

SUPPORT .NET 6.0 AND STANDARD 2.0

**Comment by RikuVirtanen** [comment]
Implemented Task for Downloading Files through SFTP connection following Frends Tasks guidelines and targeting net6.0, netsandard2.0 and net471. Used Cobalt as reference in the implementation.
